# Note: this action will be published separate on the GitHub.
# It's here only temporary for the development purposes.

name: 'Post Build'
description: 'Post Build info'

inputs:
  artifact-url:
    description: 'The URL of the artifact to post'
    required: true
  title:
    description: 'The title of the GitHub comment'
    required: true
  github-token:
    description: A GitHub Personal Access Token with write access to the project
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
