name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build-simulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install
